routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Laporan;
use App\Http\Controllers\Laporanpaket;
// use App\Http\Controllers\Admin\LaporanBokingController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [\App\Http\Controllers\BookingController::class, 'index'])->name('booking.index');
Route::get('booking/create', [\App\Http\Controllers\BookingController::class, 'booking'])->name('booking')->middleware('auth');
Route::post('booking', [\App\Http\Controllers\BookingController::class, 'store'])->name('booking.store');
Route::put('booking/{id}/edit', [\App\Http\Controllers\BookingController::class, 'edit'])->name('booking.edit');
Route::post('booking/{id}/update-status', [\App\Http\Controllers\BookingController::class, 'updateStatus'])->name('booking.updateStatus');
Route::get('booking/success/{booking}/{date}/{harga}', [\App\Http\Controllers\BookingController::class, 'success'])->name('booking.success');
Route::put('booking/uploadbukti/{id}', [\App\Http\Controllers\BookingController::class, 'uploadBukti'])->name('booking.uploadBukti');
Route::get('bookingan-saya', [\App\Http\Controllers\BookingController::class, 'mine'])->name('booking.mine');

Route::get('bookingpakets/create', [\App\Http\Controllers\BookingpaketsController::class, 'bookingpakets'])->name('bookingpakets');
Route::post('bookingpakets', [\App\Http\Controllers\BookingpaketsController::class, 'store'])->name('bookingpakets.store');
Route::get('bookingpakets/success/{bookingpakets}/{date}/{harga}', [\App\Http\Controllers\BookingpaketsController::class, 'success'])->name('bookingpakets.success');
Route::put('bookingpakets/uploadbukti/{id}', [\App\Http\Controllers\BookingpaketsController::class, 'uploadBukti'])->name('bookingpakets.uploadBukti');
Route::get('bookingan-paket-saya', [\App\Http\Controllers\BookingpaketsController::class, 'mine'])->name('booking-paket.mine');
Route::post('booking-paket/{id}/update-status', [\App\Http\Controllers\BookingpaketsController::class, 'updateStatus'])->name('booking-paket.updateStatus');
Route::put('booking-paket/{id}/edit', [\App\Http\Controllers\BookingpaketsController::class, 'edit'])->name('booking-paket.edit');


Route::post('event/booking', [\App\Http\Controllers\Admin\DashboardController::class, 'store'])->name('event.store');
Route::group(['middleware' => ['isAdmin', 'auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', [\App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard.index');



    Route::resource('permissions', \App\Http\Controllers\Admin\PermissionController::class);
    Route::delete('permissions_mass_destroy', [\App\Http\Controllers\Admin\PermissionController::class, 'massDestroy'])->name('permissions.mass_destroy');
    Route::resource('roles', \App\Http\Controllers\Admin\RoleController::class);
    Route::delete('roles_mass_destroy', [\App\Http\Controllers\Admin\RoleController::class, 'massDestroy'])->name('roles.mass_destroy');
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
    Route::delete('users_mass_destroy', [\App\Http\Controllers\Admin\UserController::class, 'massDestroy'])->name('users.mass_destroy');

    Route::resource('studios', \App\Http\Controllers\Admin\StudiosController::class);
    Route::post('studios/media', [\App\Http\Controllers\Admin\StudiosController::class, 'storeMedia'])->name('studios.storeMedia');
    Route::delete('studios_mass_destroy', [\App\Http\Controllers\Admin\StudiosController::class, 'massDestroy'])->name('studios.mass_destroy');

    Route::resource('bookings', \App\Http\Controllers\Admin\BookingController::class);
    Route::delete('bookings_mass_destroy', [\App\Http\Controllers\Admin\BookingController::class, 'massDestroy'])->name('bookings.mass_destroy');

    Route::resource('services', \App\Http\Controllers\Admin\ServicesController::class);
    Route::delete('services_mass_destroy', [\App\Http\Controllers\Admin\ServicesController::class, 'massDestroy'])->name('services.mass_destroy');
    Route::post('services/media', [\App\Http\Controllers\Admin\ServicesController::class, 'storeMedia'])->name('services.storeMedia');

    Route::resource('bookingpaket', \App\Http\Controllers\Admin\BookingpaketController::class);
    Route::delete('bookingpaket_mass_destroy', [\App\Http\Controllers\Admin\BookingpaketController::class, 'massDestroy'])->name('bookingpaket.mass_destroy');

    Route::resource('laporan', \App\Http\Controllers\Admin\LaporanPaketController::class);
    // Route::get('laporan/boking', \App\Http\Controllers\Admin\LaporanPaketController::class);

    Route::get('laporan_booking', [\App\Http\Controllers\Admin\LaporanBokingController::class, 'index'])->name('laporan.booking');
    Route::post('laporan_booking/search', [\App\Http\Controllers\Admin\LaporanBokingController::class, 'laporanSearch']);

    Route::post('laporan/search', [\App\Http\Controllers\Admin\LaporanPaketController::class, 'laporanSearch']);

    // Route::get('laporan/transaksi', 'ReportController@transaksi');
});

Auth::routes();

app/Models/Services.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use PhpParser\Node\Expr\Cast\Bool_;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Services extends Model implements HasMedia
{
    use HasFactory,InteractsWithMedia;

    protected $appends = [
        'photo',
    ];
    
    protected $guarded = ['id', 'created_at', 'updated_at'];

    public function getPhotoAttribute()
    {
        $file = $this->getMedia('photo')->last();

        if ($file) {
            $file->url       = $file->getUrl();
        }

        return $file;
    }

    public function getStatusAttribute($input){
        return [
            0 => 'In Active',
            1 => 'Active'
        ][$input];
    }

    public function bookingpaket(){
        return $this->hasOne(Bookingpaket::class, 'services_id');
    }
}

app/Http/Controllers/Admin/ServicesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Services;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\Admin\ServicesRequest;
use Symfony\Component\HttpFoundation\Response;

class ServicesController extends Controller
{
    use MediaUploadingTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        abort_if(Gate::denies('services_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $services = Services::all();

        return view('admin.services.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('services_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        return view('admin.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ServicesRequest $request)
    // public function store(Request $request)
    {
        // dd($request->all());
        abort_if(Gate::denies('services_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $service = Services::create($request->validated() + [
            'jam_paket' => $request->jam_paket,
            'jenis_paket' => $request->jenis_paket,
            'denda' => $request->denda,
        ]);
        if ($request->input('photo', false)) {
            $service->addMedia(storage_path('tmp/uploads/' . $request->input('photo')))->toMediaCollection('photo');
        }

        return redirect()->route('admin.services.index')->with([
            'message' => 'successfully created !',
            'alert-type' => 'success'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Services $service)
    {
        abort_if(Gate::denies('services_view'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        return view('admin.services.show', compact('service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Services $service)
    {
        abort_if(Gate::denies('services_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        return view('admin.services.edit', compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ServicesRequest $request, Services $service)
    {
        abort_if(Gate::denies('services_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $service->update($request->validated() + [
            'jam_paket' => $request->jam_paket,
            'jenis_paket' => $request->jenis_paket,
            'denda' => $request->denda,
        ]);

        if ($request->input('photo', false)) {
            if (!$service->photo || $request->input('photo') !== $service->photo->file_name) {
                $service->addMedia(storage_path('tmp/uploads/' . $request->input('photo')))->toMediaCollection('photo');
            }
        } elseif ($service->photo) {
            $service->photo->delete();
        }
        return redirect()->route('admin.services.index')->with([
            'message' => 'successfully updated !',
            'alert-type' => 'success'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Services $service)
    {
        abort_if(Gate::denies('services_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $service->delete();

        return redirect()->route('admin.services.index')->with([
            'message' => 'successfully deleted !',
            'alert-type' => 'success'
        ]);
    }

    /**
     * Delete all selected Permission at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        abort_if(Gate::denies('services_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        Services::whereIn('id', request('ids'))->delete();

        return response()->noContent();
    }
}

resources/views/admin/services/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->


    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <!-- Content Row -->
    <div class="card shadow">
        <div class="card-body">
            <form action="{{ route('admin.services.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="services_id">Jenis Paket</label>
                    <select name="jenis_paket" id="jenis_paket" class="form-control">
                        <option value="A">A</option>
                        <option value="B">B</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">{{ __('name') }}</label>
                    <input type="text" class="form-control" id="name" placeholder="{{ __('name') }}" name="name"
                        value="{{ old('name') }}" />
                </div>
                <div class="form-group">
                    <label for="price">{{ __('Harga ') }}</label>
                    <input type="number" class="form-control" id="price" placeholder="{{ __('price') }}" name="price"
                        value="{{ old('price') }}" />
                </div>
                <div class="form-group">
                    <label for="jam_paket">{{ __('jumlah jam') }}</label>
                    <input type="number" class="form-control" id="jam_paket" placeholder="{{ __('jam_paket') }}"
                        name="jam_paket" value="{{ old('jam_paket') }}" />
                    <span class="text-secondary">Jika kosong maka user bisa mengisi jam terserah</span>
                </div>
                <div class="form-group">
                    <label for="name">{{ __('Denda') }}</label>
                    <input type="text" class="form-control" id="denda" placeholder="{{ __('denda') }}" name="denda"
                        value="{{ old('denda') }}" />
                </div>
                <div class="form-group {{ $errors->has('photo') ? 'has-error' : '' }}">
                    <label for="photo">Photo</label>
                    <div class="needsclick dropzone" id="photo-dropzone">

                    </div>
                    @if($errors->has('photo'))
                    <em class="invalid-feedback">
                        {{ $errors->first('photo') }}
                    </em>
                    @endif
                </div>
                <div class="form-group">
                    <label for="status">{{ __('Status') }}</label>
                    <select name="status" id="status" class="form-control">
                        <option value="1">Active</option>
                        <option value="0">In Active</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary btn-block">{{ __('Save') }}</button>
            </form>
        </div>
    </div>


    <!-- Content Row -->

</div>
@endsection

@push('style-alt')
<link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css" rel="stylesheet" />
@endpush

@push('script-alt')
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
<script>
Dropzone.options.photoDropzone = {
    url: "{{ route('admin.services.storeMedia') }}",
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
        'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
        size: 2,
        width: 4096,
        height: 4096
    },
    success: function(file, response) {
        $('form').find('input[name="photo"]').remove()
        $('form').append('<input type="hidden" name="photo" value="' + response.name + '">')
    },
    removedfile: function(file) {
        file.previewElement.remove()
        if (file.status !== 'error') {
            $('form').find('input[name="photo"]').remove()
            this.options.maxFiles = this.options.maxFiles + 1
        }
    },
    init: function() {
        @if(isset($services))
        var file = {
            !!json_encode('{{$services->photo}}') !!
        }
        this.options.addedfile.call(this, file)
        this.options.thumbnail.call(this, file, "{{ $services->photo->getUrl() }}")
        file.previewElement.classList.add('dz-complete')
        $('form').append('<input type="hidden" name="photo" value="' + file.file_name + '">')
        this.options.maxFiles = this.options.maxFiles - 1
        @endif
    },
    error: function(file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }
        return _results
    }
}
</script>
@endpush

resources/views/admin/services/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->


    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <!-- Content Row -->
    <div class="card shadow">
        <div class="card-header">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">{{ __('Edit paket') }}</h1>
                <a href="{{ route('admin.services.index') }}"
                    class="btn btn-primary btn-sm shadow-sm">{{ __('Go Back') }}</a>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('admin.services.update', $service->id) }}" method="POST"
                enctype="multipart/form-data">
                @csrf
                @method('put')<div class="form-group">
                    <label for="services_id">Jenis Paket</label>
                    <select name="jenis_paket" id="jenis_paket" class="form-control">
                        <option @if($service->jenis_paket == 'A') selected @endif value="A">A</option>
                        <option @if($service->jenis_paket == 'B') selected @endif value="B">B</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">{{ __('name') }}</label>
                    <input type="text" class="form-control" id="name" placeholder="{{ __('name') }}" name="name"
                        value="{{ old('name', $service->name) }}" />
                </div>
                <div class="form-group">
                    <label for="price">{{ __('Harga ') }}</label>
                    <input type="number" class="form-control" id="price" placeholder="{{ __('price') }}" name="price"
                        value="{{ old('price', $service->price) }}" />
                </div>
                <div class="form-group">
                    <label for="name">{{ __('Denda') }}</label>
                    <input type="text" class="form-control" id="denda" placeholder="{{ __('denda') }}" name="denda"
                        value="{{ old('denda', $service->denda) }}" />
                </div>
                <div class="form-group {{ $errors->has('photo') ? 'has-error' : '' }}">
                    <label for="photo">Photo</label>
                    <div class="needsclick dropzone" id="photo-dropzone">

                    </div>
                    @if($errors->has('photo'))
                    <em class="invalid-feedback">
                        {{ $errors->first('photo') }}
                    </em>
                    @endif
                </div>
                <div class="form-group">
                    <label for="status">{{ __('Status') }}</label>
                    <select name="status" id="status" class="form-control">
                        <option {{ $service->status == 'Active' ? 'selected' : null }} value="1">Active</option>
                        <option {{ $service->status == 'In Active' ? 'selected' : null }} value="0">In Active</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary btn-block">{{ __('Save') }}</button>
            </form>
        </div>
    </div>


    <!-- Content Row -->

</div>
@endsection


@push('style-alt')
<link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css" rel="stylesheet" />
@endpush

@push('script-alt')
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
<script>
Dropzone.options.photoDropzone = {
    url: "{{ route('admin.services.storeMedia') }}",
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
        'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
        size: 2,
        width: 4096,
        height: 4096
    },
    success: function(file, response) {
        $('form').find('input[name="photo"]').remove()
        $('form').append('<input type="hidden" name="photo" value="' + response.name + '">')
    },
    removedfile: function(file) {
        file.previewElement.remove()
        if (file.status !== 'error') {
            $('form').find('input[name="photo"]').remove()
            this.options.maxFiles = this.options.maxFiles + 1
        }
    },
    init: function() {
        @if(isset($services) && $services->photo)
        var file = {
            !!json_encode($services->photo) !!
        }
        this.options.addedfile.call(this, file)
        this.options.thumbnail.call(this, file, "{{ $services->photo->getUrl() }}")
        file.previewElement.classList.add('dz-complete')
        $('form').append('<input type="hidden" name="photo" value="' + file.file_name + '">')
        this.options.maxFiles = this.options.maxFiles - 1
        @endif
    },
    error: function(file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }
        return _results
    }
}
</script>
@endpush

resources/views/admin/services/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->


    <!-- Content Row -->
    <div class="card">
        <div class="card-header py-3 d-flex">
            <h6 class="m-0 font-weight-bold text-primary">
                {{ __('Paket') }}
            </h6>
            <div class="ml-auto">
                @can('booking_create')
                <a href="{{ route('admin.services.create') }}" class="btn btn-primary">
                    <span class="icon text-white-50">
                        <i class="fa fa-plus"></i>
                    </span>
                    <span class="text">{{ __('Buat paket') }}</span>
                </a>
                @endcan
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover datatable datatable-service"
                    cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th width="10">

                            </th>
                            <th>No</th>
                            <th>Nama</th>
                            <th>jenis paket</th>
                            <th>Harga</th>
                            <th>Gambar</th>
                            <th>Denda</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($services as $service)
                        <tr data-entry-id="{{ $service->id }}">
                            <td>

                            </td>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $service->name }}</td>
                            <td>{{ $service->jenis_paket }}</td>
                            <td>Rp{{ number_format($service->price,2,',','.') }}</td>
                            <td>
                                @if($service->photo)
                                <a href="{{ $service->photo->getUrl() }}" target="_blank">
                                    <img src="{{ url('/'). $service->photo->getUrl() }}" width="50px" height="50px">
                                </a>
                                @endif
                            </td>
                            <td>Rp{{ number_format($service->denda,2,',','.') }}</td>
                            <td>{{ $service->status }}</td>
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a href="{{ route('admin.services.edit', $service->id) }}" class="btn btn-info">
                                        <i class="fa fa-pencil-alt"></i>
                                    </a>
                                    <form onclick="return confirm('are you sure ? ')" class="d-inline"
                                        action="{{ route('admin.services.destroy', $service->id) }}" method="POST">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger"
                                            style="border-top-left-radius: 0;border-bottom-left-radius: 0;">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="7" class="text-center">{{ __('Data Empty') }}</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Content Row -->

</div>
@endsection

@push('script-alt')
<script>
$(function() {
    let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
    let deleteButtonTrans = 'delete selected'
    let deleteButton = {
        text: deleteButtonTrans,
        url: "{{ route('admin.services.mass_destroy') }}",
        className: 'btn-danger',
        action: function(e, dt, node, config) {
            var ids = $.map(dt.rows({
                selected: true
            }).nodes(), function(entry) {
                return $(entry).data('entry-id')
            });
            if (ids.length === 0) {
                alert('zero selected')
                return
            }
            if (confirm('are you sure ?')) {
                $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        method: 'POST',
                        url: config.url,
                        data: {
                            ids: ids,
                            _method: 'DELETE'
                        }
                    })
                    .done(function() {
                        location.reload()
                    })
            }
        }
    }
    dtButtons.push(deleteButton)
    $.extend(true, $.fn.dataTable.defaults, {
        order: [
            [1, 'asc']
        ],
        pageLength: 50,
    });
    $('.datatable-service:not(.ajaxTable)').DataTable({
        buttons: dtButtons
    })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})
</script>
@endpush